# Generated by Django 3.1.5 on 2021-01-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('photo', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('link', models.URLField()),
            ],
        ),
    ]
