# Generated by Django 3.1.5 on 2021-01-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rating.project'),
        ),
    ]
